### ISSUE TITLE
Refactor DistanceProxy

### ISSUE THREAD

**Issue by Genbox** [VelcroPhysics/VelcroPhysics#23]
It basically wraps vertices by copying over the data from shapes. Distance calculation should not have anything to do with shapes or proxies, so we could simplify the code by reducing the proxies to vertices and radius in a struct. The mapping between shapes such as CircleShape could then be simplified by enforcing Shape to have Vertices, where CircleShape would just have 1 vertex (its position).

**Comment by bQvle** [comment]
Unrelated..

Just want to let you know that I'm really happy to see you're back 👍 
I'm currently using farseer and was under the impression that it was put to rest for good.

Is there any specific reason you are reviving it?

(Im using farseer at tankwars.io, we had some conversation via mail about a year ago about some problems i had because of threading)

Right now its running without any problems. but I'm looking forward to improvement and optimizations :)
