### ISSUE TITLE
Can't run HelloWorld project on VS 2017

### ISSUE THREAD

**Issue by HoDuyQuang** [VelcroPhysics/VelcroPhysics#49]
![missing2](https://user-images.githubusercontent.com/17638038/33368862-68a331ac-d525-11e7-95ac-17e6b97565fd.PNG)
When I open the solution, `Game`, `Microsoft.Xna.Framework.Graphics`, `Microsoft.Xna.Framework.Input`,... can not be resolve.
Do I need install any missing library? I can't fix MonoGame.Framework reference missing in project. Please help me!

```
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Inp
![missing](https://user-images.githubusercontent.com/17638038/33368832-52e03cb6-d525-11e7-9834-455b39b1dbad.PNG)
ut;
namespace VelcroPhysics.Samples.HelloWorld
{
    public class Game1 : Game
...
}
```
![missing](https://user-images.githubusercontent.com/17638038/33368885-7903d2cc-d525-11e7-95ba-6f8a36152e54.PNG)

**Comment by Crumbler** [comment]
Judging by the errors, you need to install [xna framework](https://www.microsoft.com/en-us/search/result.aspx?q=xna). VelcroPhysics user the Vector2 class from it.

**Comment by Crumbler** [comment]
Juding by the error, you need to install [xna framework](https://www.microsoft.com/en-us/download/details.aspx?id=20914). VelcroPhysics uses the Vector2 class from it.

**Comment by Crumbler** [comment]
Judgin by the erros, you need to install [xna framework](https://www.microsoft.com/en-us/download/details.aspx?id=20914). VelcroPhysics uses the Vector2 class from it.

**Comment by Crumbler** [comment]
Judging by the errors, you need to install [xna framework](https://www.microsoft.com/en-us/download/details.aspx?id=20914). VelcroPhysics uses the Vector2 class from it.

**Comment by Genbox** [comment]
You need to install the latest version of [MonoGame](http://www.monogame.net/downloads/) to use the MonoGame solution. VelcroPhysics does not depend on XNA/MonoGame. If you open the normal "VelcroPhysics.sln" solution file, you'll see that Vector2 and all the other classes that usually come from MonoGame are already there.

If you are going to use MonoGame for your application, you should use the MonoGame version since it links to the Vector2 etc. from the library, and you therefore don't have to copy between MonoGame's Vector2 and the one in VelcroPhysics.
